import { Breadcrumbs } from "@/components/shared";
import { BreadcrumbSchema } from "@/app/schema";
import { createPageMetadata } from "@/lib/page-metadata";

export const metadata = createPageMetadata({ title: "Terms of Service", description: "Terms for PujaPath puja enquiries and coordination.", path: "/terms" });

export default function TermsPage() {
  return <><BreadcrumbSchema items={[{ label: "Home", href: "/" }, { label: "Terms", href: "/terms" }]} /><section className="page-intro"><div className="content-wrap"><Breadcrumbs items={[{ label: "Terms" }]} /><span className="eyebrow">Service terms</span><h1>Terms of service</h1><p>These terms explain what happens when you ask PujaPath about a ritual.</p></div></section><section className="section"><div className="content-wrap"><div className="info-panel"><h2>Enquiries and bookings</h2><p>Sending an enquiry on WhatsApp is a request for information. It does not reserve a Pandit, confirm availability, set a price or create a confirmed booking. The PujaPath team will discuss the ritual, date, location, arrangements and any quote with you. A booking is confirmed only after you and the team agree those details directly.</p><h2>Ritual information</h2><p>Puja descriptions, durations and samagri lists on this site are general guidance. Customs and preparation can vary by family and region; confirm your requirements with the team before the ceremony.</p><h2>Changes and cancellations</h2><p>Contact the team as soon as your plans change. Any revised date depends on availability. Payment, cancellation and rescheduling terms will be shared with you before a booking is finalized.</p><div className="legal-note">These terms should be reviewed for your business and the places where you provide services.</div></div></div></section></>;
}
